export const erc20Abi = [
  {
    type: 'function',
    name: 'allowance',
    stateMutability: 'view',
    inputs: [
      { name: 'owner', type: 'address' },
      { name: 'spender', type: 'address' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'approve',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'spender', type: 'address' },
      { name: 'value', type: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'balanceOf',
    stateMutability: 'view',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
]

export const atlasPoolAbi = [
  {
    type: 'function',
    name: 'depositPremium',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'member', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'claimsContract',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'feeBps',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint16' }],
  },
  {
    type: 'function',
    name: 'poolBalance',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'premiumByMember',
    stateMutability: 'view',
    inputs: [{ name: 'member', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'getPoolSnapshot',
    stateMutability: 'view',
    inputs: [],
    outputs: [
      { name: 'usdcAddress', type: 'address' },
      { name: 'treasury', type: 'address' },
      { name: 'platformFeeBps', type: 'uint16' },
      { name: 'communityPoolBalance', type: 'uint256' },
      { name: 'treasuryCollected', type: 'uint256' },
      { name: 'claims', type: 'address' },
    ],
  },
  {
    type: 'function',
    name: 'totalTreasuryCollected',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'treasuryWallet',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'event',
    name: 'PremiumDeposited',
    inputs: [
      { indexed: true, name: 'member', type: 'address' },
      { indexed: true, name: 'payer', type: 'address' },
      { indexed: false, name: 'grossAmount', type: 'uint256' },
      { indexed: false, name: 'poolAmount', type: 'uint256' },
      { indexed: false, name: 'treasuryAmount', type: 'uint256' },
    ],
    anonymous: false,
  },
]

export const atlasClaimsAbi = [
  {
    type: 'function',
    name: 'nextClaimId',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'submitClaim',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'category', type: 'string' },
      { name: 'evidenceUri', type: 'string' },
      { name: 'description', type: 'string' },
      { name: 'requestedAmount', type: 'uint256' },
      { name: 'externalReference', type: 'string' },
    ],
    outputs: [{ name: 'claimId', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'submitClaimFor',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'member', type: 'address' },
      { name: 'category', type: 'string' },
      { name: 'evidenceUri', type: 'string' },
      { name: 'description', type: 'string' },
      { name: 'requestedAmount', type: 'uint256' },
      { name: 'externalReference', type: 'string' },
    ],
    outputs: [{ name: 'claimId', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'resolveAndPayClaim',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'claimId', type: 'uint256' },
      { name: 'approved', type: 'bool' },
      { name: 'payoutAmount', type: 'uint256' },
      { name: 'verdictUri', type: 'string' },
      { name: 'juryReference', type: 'string' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'queueClaimForVerdict',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'claimId', type: 'uint256' },
      { name: 'juryReference', type: 'string' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'claims',
    stateMutability: 'view',
    inputs: [{ name: 'claimId', type: 'uint256' }],
    outputs: [
      { name: 'member', type: 'address' },
      { name: 'category', type: 'string' },
      { name: 'evidenceUri', type: 'string' },
      { name: 'description', type: 'string' },
      { name: 'requestedAmount', type: 'uint256' },
      { name: 'approvedAmount', type: 'uint256' },
      { name: 'status', type: 'uint8' },
      { name: 'submittedAt', type: 'uint64' },
      { name: 'verdictUri', type: 'string' },
      { name: 'externalReference', type: 'string' },
      { name: 'juryReference', type: 'string' },
    ],
  },
  {
    type: 'event',
    name: 'ClaimSubmitted',
    inputs: [
      { indexed: true, name: 'claimId', type: 'uint256' },
      { indexed: true, name: 'member', type: 'address' },
      { indexed: false, name: 'category', type: 'string' },
      { indexed: false, name: 'requestedAmount', type: 'uint256' },
      { indexed: false, name: 'externalReference', type: 'string' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ClaimResolved',
    inputs: [
      { indexed: true, name: 'claimId', type: 'uint256' },
      { indexed: true, name: 'member', type: 'address' },
      { indexed: false, name: 'approved', type: 'bool' },
      { indexed: false, name: 'approvedAmount', type: 'uint256' },
      { indexed: false, name: 'juryReference', type: 'string' },
    ],
    anonymous: false,
  },
]
